<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.props))\DjvuNetBuild.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>DjvuNetTest</RootNamespace>
    <AssemblyName>DjvuNetTest</AssemblyName>
    <IsDjvuNetTestProject>True</IsDjvuNetTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <_HasReferenceToSystemRuntime>true</_HasReferenceToSystemRuntime>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DjvuNetPerfTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestFiles\Mcguffey%27s_Primer.djvu" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="$(LibGit2SharpPackageVersion)" />
    <PackageReference Include="System.Drawing.Common" Version="$(SystemDrawingCommonPackageVersion)" Condition="'$(TargetOS)' == 'Windows'" />
    <Reference Include="System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9a0646c3e445b595" Condition="'$(TargetOS)' != 'Windows'">
      <HintPath>$(RepoRootDir)deps/AnyCPU/$(Configuration)/Unix/System.Drawing.Common.dll</HintPath>
    </Reference>
    <PackageReference Include="xunit.v3" Version="$(XunitPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DjvuNet\DjvuNet.csproj" />
    <ProjectReference Include="..\System.Attributes\System.Attributes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DjvuNet.Shared.Tests\DjvuNet.Shared.Tests.csproj" />
  </ItemGroup>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.targets))\DjvuNetBuild.targets" />
  <Import Project="..\DjvuNet.DjvuLibre\DjvuNet.DjvuLibre.targets" />

</Project>
