image: Visual Studio 2015

version: '0.7.0.{build}'

platform:
  - x86
  - x64
  - AnyCPU

configuration:
  - Debug
  - Release

branches:
  only:
    - parser_archit
    - master

# clone directory
clone_folder: c:\projects\djvunet

# shallow_clone: true 

# block DjvuNet testing until test data committed and described
test:
  categories:
    except:
      - Skip

matrix:
  fast_finish: true

cache:
    - packages -> **\packages.config  

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

init:
    - git config --global core.autocrlf false

install:
    - cmd: cd c:\projects\djvunet
    - cmd: git clone https://github.com/DjvuNet/DjVuLibre

before_build:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - appveyor-retry nuget restore -DisableParallelProcessing  -verbosity detailed

build:
    project: DjvuNet.sln
    verbosity: detailed

#test_script:
#