image: Visual Studio 2015

version: '0.7.0.{build}'

platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

branches:
  only:
    - parser_archit
# block testing until test data committed
test:
  categories:
    only:
      - NonExistingCategory
matrix:
  fast_finish: true

before_build:
    nuget restore -DisableParallelProcessing  -verbosity detailed