image: Visual Studio 2015

version: '0.7.0.{build}'

platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

branches:
  only:
    - parser_archit
    - master

# clone directory
clone_folder: c:\projects\djvunet

# shallow_clone: true 

# block testing until test data committed
test:
  categories:
    only:
      - NonExistingCategory
matrix:
  fast_finish: true

cache:
    - packages -> **\packages.config   

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

install:
    - cmd: cd c:\projects\djvunet
    - cmd: git clone https://github.com/DjvuNet/DjVuLibre


before_build:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - appveyor-retry nuget restore -DisableParallelProcessing  -verbosity detailed

build:
    project: DjvuNet.sln
    verbosity: detailed