image: Visual Studio 2017

version: '0.7.0.{build}'

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
#    - parser_archit
    - master

# clone directory
clone_folder: c:\projects\djvunet

# Force git at least 1 commit depth repo which is equivalent to zip download
# but has git repo with last commit - it allows to retrieve commit hash
# during build and using it for assembly attributes initialization
# clone_depth: 10

test:
  categories:
    except:
      - Skip

matrix:
  fast_finish: true

cache:
#    - packages -> **\packages.config
#    - artifacts -> artifacts.sha256

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

init:
    - cmd: git config --global core.autocrlf false

install:
    - cmd: cd c:\projects\djvunet
    - cmd: git clone https://github.com/DjvuNet/DjVuLibre.git
    - appveyor DownloadFile https://github.com/DjvuNet/artifacts/releases/download/v0.7.0.11/artifacts.zip
    - cmd: 7z x -oartifacts artifacts.zip

before_build:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - appveyor-retry nuget restore c:\projects\djvunet\DjvuNet.sln -DisableParallelProcessing  -verbosity detailed

build:
    project: DjvuNet.sln
    verbosity: detailed
