image: Visual Studio 2015

version: '0.7.0.{build}'

platform:
  - x86
  - x64
  - AnyCPU

configuration:
  - Debug
  - Release

branches:
  only:
    - parser_archit
    - master

# clone directory
clone_folder: c:\projects\djvunet

# shallow_clone: true 

# block DjvuNet testing until test data committed and described
test:
  categories:
    except:
      - Skip

matrix:
  fast_finish: true

cache:
    - packages -> **\packages.config
    - artifacts\**
    - deps\**   

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

install:
    - cmd: cd c:\projects\djvunet
    - cmd: git clone https://github.com/DjvuNet/DjVuLibre


before_build:
    - appveyor-retry DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - appveyor-retry nuget restore -DisableParallelProcessing  -verbosity detailed

build:
    project: DjvuNet.sln
    verbosity: detailed

test_script:
    - cmd: cd c:\projects\DjvuNet
    - cmd: packages\xunit.runner.console.2.2.0\tools\xunit.console.exe DjvuNet.Tests\bin\$(platform)\$(configuration)\DjvuNet.Tests.dll /appveyor
    - cmd: packages\xunit.runner.console.2.2.0\tools\xunit.console.exe DjvuNet.DjvuLibre.Tests\bin\$(platform)\$(configuration)\DjvuNet.Tests.dll /appveyor