image: Visual Studio 2019

version: '0.8.0.{build}'

platform:
#  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - dev
    - master
    - dotnet30

# clone directory
clone_folder: c:\projects\djvunet

# Force git at least 1 commit depth repo which is equivalent to zip download
# but has git repo with last commit - it allows to retrieve commit hash
# during build and using it for assembly attributes initialization
# clone_depth: 10

test:
  categories:
    except:
      - Skip

matrix:
  fast_finish: false

# Maximum number of concurrent jobs for the project
max_jobs: 4

cache:
#    - packages -> **\packages.config
#    - artifacts -> artifacts.sha256

# environment variables
environment:
    TargetFramework: netcoreapp3.0
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

init:
    - cmd: git config --global core.autocrlf false

install:
    - cmd: echo Publish directory [%PublishDir%]
    - cmd: cd c:\projects\djvunet

build_script:
    - cmd: build -p %PLATFORM% -c %CONFIGURATION% -f netcoreapp3.0 -sn -Test

test_script:
    - cmd: echo DjvuNet [%PLATFORM%] [%CONFIGURATION%] build by AppVeyor
