image: Visual Studio 2015

version: '0.7.0.{build}'

platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

branches:
  only:
    - parser_archit
# block testing until test data committed
test:
  categories:
    only:
      - NonExistingCategory
matrix:
  fast_finish: true

cache:
    - packages -> **\packages.config    

############################################################################
#
#  BUILD SEQUENCE
#
############################################################################

install:
    # Get latest nuget.exe version
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
    appveyor-retry nuget restore -DisableParallelProcessing  -verbosity detailed

