#
#

language: csharp

os:
  - linux
  - osx

dist: trusty
sudo: required
osx_image: xcode8.3

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

solution: DjvuNet.sln

mono: none
dotnet: 2.0.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mono-libgdiplus; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zip unzip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgdiplus; fi

install:


script:
    - chmod u+x build.sh
    - git clone --depth 1 https://github.com/DjvuNet/DjVuLibre.git DjVuLibre
    - curl -L -o artifacts.zip -s https://github.com/DjvuNet/artifacts/releases/download/v0.7.0.11/artifacts.zip
    - unzip -q artifacts.zip -d artifacts
    - dotnet restore DjvuNet.sln
    - cd DjvuNet
    - dotnet msbuild /m /nologo /p:Configuration=Debug /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet msbuild /m /nologo /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet msbuild /m /nologo /p:Configuration=Debug /p:Platform=x64 /p:TargetFramework=netstandard2.0 /t:Build
    - dotnet msbuild /m /nologo /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=netstandard2.0 /t:Build
    - cd ..
    - cd DjvuNet.Tests
    - dotnet msbuild /m /nologo /p:Configuration=Debug /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet xunit -configuration Debug -parallel none -nobuild -notrait Category=SkipNetCoreApp -framework netcoreapp2.0 ../build/x64/Debug/netcoreapp2.0/DjvuNet.Tests.dll
    - dotnet msbuild /m /nologo /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet xunit -configuration Release -parallel none -nobuild -notrait Category=SkipNetCoreApp -framework netcoreapp2.0 ../build/x64/Release/netcoreapp2.0/DjvuNet.Tests.dll
    - cd ..
    - cd DjvuNet.Wavelet.Tests
    - dotnet msbuild /m /nologo /p:Configuration=Debug /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet xunit -configuration Debug -parallel none -nobuild -notrait Category=SkipNetCoreApp -framework netcoreapp2.0 ../build/x64/Debug/netcoreapp2.0/DjvuNet.Wavelet.Tests.dll
    - dotnet msbuild /m /nologo /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=netcoreapp2.0 /t:Build
    - dotnet xunit -configuration Release -parallel none -nobuild -notrait Category=SkipNetCoreApp -framework netcoreapp2.0 ../build/x64/Release/netcoreapp2.0/DjvuNet.Wavelet.Tests.dll
