<Project ToolsVersion="16.0">

  <!-- NuGet package restore sources. -->
  <PropertyGroup>
    <RestoreSources>
      https://api.nuget.org/v3/index.json;
      $(RestoreSources)
    </RestoreSources>
  </PropertyGroup>

  <!-- Project dependency versions. -->
  <PropertyGroup>
    <MicrosoftNETCorePlatformsPackageVersion>10.0.10</MicrosoftNETCorePlatformsPackageVersion>
    <MicrosoftNETCoreAppPackageVersion>10.0.10</MicrosoftNETCoreAppPackageVersion>
    <MicrosoftNETCoreRuntimeCoreCLRPackageVersion>$(MicrosoftNETCoreAppPackageVersion)</MicrosoftNETCoreRuntimeCoreCLRPackageVersion>
    <MicrosoftNETCoreDotNetAppHostPackageVersion>$(MicrosoftNETCoreAppPackageVersion)</MicrosoftNETCoreDotNetAppHostPackageVersion>
    <MicrosoftNETCoreDotnetHostResolverPackageVersion>$(MicrosoftNETCoreAppPackageVersion)</MicrosoftNETCoreDotnetHostResolverPackageVersion>
    <MicrosoftNETCoreDotnetHostPolicyPackageVersion>$(MicrosoftNETCoreAppPackageVersion)</MicrosoftNETCoreDotnetHostPolicyPackageVersion>
    <XunitPackageVersion>3.2.2</XunitPackageVersion>
    <MoqPackageVersion>4.20.72</MoqPackageVersion>
    <MicrosoftBuildPackageVersion>18.7.1</MicrosoftBuildPackageVersion>
    <LibGit2SharpPackageVersion>0.31.0</LibGit2SharpPackageVersion>
    <LibGit2SharpNativeBinariesPackageVersion>2.0.323</LibGit2SharpNativeBinariesPackageVersion>
    <MinVerPackageVersion>7.0.0</MinVerPackageVersion>
    <SystemDrawingCommonPackageVersion Condition="'$(TargetOS)' == 'Windows'">$(MicrosoftNETCoreAppPackageVersion)</SystemDrawingCommonPackageVersion>
    <SystemDrawingCommonPackageVersion Condition="'$(TargetOS)' != 'Windows'">6.0.0</SystemDrawingCommonPackageVersion>
    <SkiaSharpPackageVersion>3.119.2</SkiaSharpPackageVersion>
    <SystemCommandLinePackageVersion>2.0.8</SystemCommandLinePackageVersion>
  </PropertyGroup>

  <!-- ILLink.Tasks package version -->
  <PropertyGroup>
    <MicrosoftILLinkTasksPackage>Microsoft.NET.ILLink.Tasks</MicrosoftILLinkTasksPackage>
    <MicrosoftILLinkTasksPackageVersion>$(MicrosoftNETCoreAppPackageVersion)</MicrosoftILLinkTasksPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <XUnitDependency Include="xunit.v3"/>
    <XUnitDependency Include="xunit.v3.assert"/>
    <XUnitDependency Include="xunit.v3.core"/>
    <XUnitDependency Include="xunit.v3.extensibility.core" />
    <StaticDependency Include="@(XUnitDependency)">
      <Version>$(XunitPackageVersion)</Version>
    </StaticDependency>

  </ItemGroup>

  <!-- Override isolated build dependency versions with versions from Repo API. -->
  <Import Project="$(DotNetPackageVersionPropsPath)"
          Condition="'$(DotNetPackageVersionPropsPath)' != ''" />

</Project>
