<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.props))\DjvuNetBuild.props" />

    <ItemGroup>
      <Compile Include="Core\CompressionRatioColumn.cs" />
      <Compile Include="Core\CustomParallelConfig.cs" />
      <Compile Include="Core\DjvuNetBenchmarkBase.cs" />
      <Compile Include="Core\LongRunningConfig.cs" />
      <Compile Include="Core\PerOperationTimeColumn.cs" />
      <Compile Include="Core\SimdMatrixConfig.cs" />
      <Compile Include="Core\StandardConfig.cs" />
      <Compile Include="Core\ThroughputColumn.cs" />
      <Compile Include="Graphics\BitmapBlitSubSampleBenchmark.cs" />
      <Compile Include="Graphics\BitmapRleBenchmark.cs" />
      <Compile Include="JB2\JB2DictionaryCodecBenchmark.cs" />
      <Compile Include="JB2\JB2ImageBenchmarkBase.cs" />
      <Compile Include="JB2\JB2ImageCodecBenchmark.cs" />
      <Compile Include="JB2\JB2ImageRenderBenchmark.cs" />
      <Compile Include="Program.cs" />
      <Compile Include="Tools\ImageBinaryDiffBenchmark.cs" />
      <Compile Include="Tools\ImageCacheBenchmark.cs" />
      <Compile Include="Wavelet\Rgb2YCbCrHybridVsUnifiedBenchmark.cs" />
      <Compile Include="Wavelet\Rgb2YCbCrMatrixBenchmark.cs" />
      <Compile Include="Wavelet\Rgb2YCbCrUnifiedBenchmark.cs" />
      <Compile Include="Wavelet\YCbCr2RgbMatrixBenchmark.cs" />
      <Compile Include="Wavelet\YCbCr2RgbParallelSimdBenchmark.cs" />
      <Compile Include="Wavelet\YCbCrCombinedMatrixBenchmark.cs" />
      <Compile Include="Wavelet\YCbCrParallelSimdBenchmark.cs" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DjvuNet/DjvuNet.csproj" />
    <ProjectReference Include="../DjvuNet.DjvuLibre/DjvuNet.DjvuLibre.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DjvuNet.Shared.Tests/DjvuNet.Shared.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8" />
    <PackageReference Include="System.Drawing.Common" Version="$(SystemDrawingCommonPackageVersion)" Condition="'$(TargetOS)' == 'Windows'" />
    <Reference Include="System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9a0646c3e445b595" Condition="'$(TargetOS)' != 'Windows'">
      <HintPath>$(RepoRootDir)deps/AnyCPU/$(Configuration)/Unix/System.Drawing.Common.dll</HintPath>
    </Reference>
    <PackageReference Include="xunit.v3.extensibility.core" Version="$(XunitPackageVersion)" />
    <PackageReference Include="xunit.v3.assert" Version="$(XunitPackageVersion)" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.targets))\DjvuNetBuild.targets" />
</Project>
