// THIS FILE IS AUTOMATICALLY GENERATED DURING BUILD!
// Apply any changes intended to appear in UtilRoot.cs to 'UtilRoot.Template.cs' template, instead.

using System;

namespace DjvuNet.Tests
{
    public static partial class Util
    {
        public static string RepoRoot { get { return @"E:\src\tools\sci\know\FKnowSci\external\DjvuNet\"; } }
    }
}
