// THIS FILE IS AUTOMATICALLY GENERATED DURING BUILD!
// Apply any changes intended to appear in AssemblyInso.cs to 'AssemblyInfo.Template.cs' template,
// in the case of AssemblyInfoCommon.cs file apply changes to AssemblyInfoCommon.Template.cs file in root folder instead.

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyCompany("DjvuNet")]
[assembly: AssemblyProduct("DjvuNet Library")]
[assembly: AssemblyCopyright("Copyright © by Telavian 2014, Copyright © by Jacek Blaszczynski 2017")]
[assembly: AssemblyTrademark("DjvuNet")]


[assembly: ComVisible(false)]


[assembly: AssemblyVersion("0.7.0.44341")]
[assembly: AssemblyFileVersion("0.7.0.44341")]
[assembly: AssemblyInformationalVersion("abff3dc35e336bbc64ca6d461f221fa5c0defab8")]

