<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.props))\DjvuNetBuild.props" />

  <PropertyGroup>

    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>DjvuNet.DjvuLibre.Tests</RootNamespace>
    <AssemblyName>DjvuNet.DjvuLibre.Tests</AssemblyName>
    <TestProjectType>UnitTest</TestProjectType>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <IsDjvuNetTestProject>True</IsDjvuNetTestProject>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Arm'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|Arm'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Arm64'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|Arm64'">
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DjvuPageInfoTests.cs" />
    <Compile Include="DjvuDocumentInfoTests.cs" />
    <Compile Include="NativeDjvuDocFixture.cs" />
    <Compile Include="NativeDjvuDocFixtureTests.cs" />
    <Compile Include="NativeMethodsTests.cs" />
    <Compile Include="JB2EncodingContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="DjvuNet.DjvuLibre.Tests.xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config">
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="$(MoqPackageVersion)" />
    <PackageReference Include="System.Drawing.Common" Version="$(SystemDrawingCommonPackageVersion)" Condition="'$(TargetOS)' == 'Windows'" />
    <Reference Include="System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9a0646c3e445b595" Condition="'$(TargetOS)' != 'Windows'">
      <HintPath>$(RepoRootDir)deps/AnyCPU/$(Configuration)/Unix/System.Drawing.Common.dll</HintPath>
    </Reference>
    <PackageReference Include="xunit.v3" Version="$(XunitPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRootDir)DjvuNet\DjvuNet.csproj" />
    <ProjectReference Include="$(RepoRootDir)DjvuNet.Tests\DjvuNet.Tests.csproj" />
    <ProjectReference Include="$(RepoRootDir)DjvuNet.DjvuLibre.Helper.Tests\DjvuNet.DjvuLibre.Helper.Tests.csproj" />
    <ProjectReference Include="$(RepoRootDir)DjvuNet.DjvuLibre\DjvuNet.DjvuLibre.csproj" />
    <ProjectReference Include="$(RepoRootDir)System.Attributes\System.Attributes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), DjvuNetBuild.targets))\DjvuNetBuild.targets" />
  <Import Project="$(RepoRootDir)DjvuNet.DjvuLibre\DjvuNet.DjvuLibre.targets" />

</Project>