name: CI Build

on:
  push:
    branches: [ "master", "djvunet-ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          # Specs: https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-VS2026-Readme.md
          - os: windows-2025-vs2026
            platform: x64
          # Specs: https://github.com/actions/runner-images/blob/main/images/windows/Windows11-Arm64-Readme.md
          - os: windows-11-arm
            platform: arm64

          # Linux
          # Specs: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
          - os: ubuntu-latest
            platform: x64
          - os: ubuntu-24.04-arm
            platform: arm64

          # macOS
          # Specs: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md
          #        https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
          - os: macos-26-intel
            platform: x64
          - os: macos-latest  # Automatically points to Apple Silicon (arm64)
            platform: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        # git, unzip, curl, zip, tar, cmake, jq, gcc, g++ are pre-installed
        sudo apt-get install -y pkg-config ninja-build autoconf automake libtool libgdiplus

        # Install cross-compilation toolchains if building for arm64 on an x64 runner
        if [ "${{ matrix.platform }}" == "arm64" ] && [ "$(uname -m)" == "x86_64" ]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        fi

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # cmake, jq, ninja, apple-clang, pkg-config are pre-installed
        brew install autoconf automake libtool mono-libgdiplus

    - name: Run Build (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        build.cmd -p ${{ matrix.platform }} -c Release -f net10.0 -Test -OS ${{ runner.os }}

    - name: Run Build (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ./build.sh -p ${{ matrix.platform }} -c Release -f net10.0 -Test -OS ${{ runner.os }}

    - name: Upload Diagnostic Logs
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: msbuild-logs-${{ matrix.os }}-${{ matrix.platform }}
        path: |
          build/bin/**/logs/
        retention-days: 2